### ISSUE TITLE
Inconsistent topbar 

### ISSUE THREAD

**Issue by ProgramistaZpolski** [TheTrollErrorsGuy65/normal-github#1]
it looks like this when in issues tab:
![Zrzut ekranu z 2020-07-02 17-36-57](https://user-images.githubusercontent.com/37271169/86379114-b7009980-bc8a-11ea-9fc9-609d97c3e4fb.png)
and it looks like this when in code tab:
![Zrzut ekranu z 2020-07-02 17-36-48](https://user-images.githubusercontent.com/37271169/86379210-dac3df80-bc8a-11ea-94cd-ae675dabed92.png)

**Comment by ProgramistaZpolski** [comment]
tldr: the topbar is centered while in the code tab but not in the issues tab.

**Comment by TheTrollErrorsGuy65** [comment]
Will be addressed in v1.5.
Keep in mind in some places it still won't be centered, like profiles. (Example: [Wayback Machine](http://web.archive.org/web/20190709001505/github.com/torvalds))

Thanks for reporting.
